USE DATABASE CPG_SUPPLY_CHAIN;
USE SCHEMA BRONZE;

--Creation of Bronze_Orders table
DROP TABLE IF EXISTS BRONZE_ORDERS;
CREATE TABLE IF NOT EXISTS BRONZE_ORDERS (
    TYPE STRING,
    DAYS_FOR_SHIPPING_REAL STRING,
    DAYS_FOR_SHIPMENT_SCHEDULED STRING,
    BENEFIT_PER_ORDER STRING,
    SALES_PER_CUSTOMER STRING,
    DELIVERY_STATUS STRING,
    LATE_DELIVERY_RISK STRING,
    CATEGORY_ID STRING,
    CATEGORY_NAME STRING,
    CUSTOMER_CITY STRING,
    CUSTOMER_COUNTRY STRING,
    CUSTOMER_EMAIL STRING,
    CUSTOMER_FNAME STRING,
    CUSTOMER_ID STRING,
    CUSTOMER_LNAME STRING,
    CUSTOMER_PASSWORD STRING,
    CUSTOMER_SEGMENT STRING,
    CUSTOMER_STATE STRING,
    CUSTOMER_STREET STRING,
    CUSTOMER_ZIPCODE STRING,
    DEPARTMENT_ID STRING,
    DEPARTMENT_NAME STRING,
    LATITUDE STRING,
    LONGITUDE STRING,
    MARKET STRING,
    ORDER_CITY STRING,
    ORDER_COUNTRY STRING,
    ORDER_CUSTOMER_ID STRING,
    ORDER_DATE_DATEORDERS STRING,
    ORDER_ID STRING,
    ORDER_ITEM_CARDPROD_ID STRING,
    ORDER_ITEM_DISCOUNT STRING,
    ORDER_ITEM_DISCOUNT_RATE STRING,
    ORDER_ITEM_ID STRING,
    ORDER_ITEM_PRODUCT_PRICE STRING,
    ORDER_ITEM_PROFIT_RATIO STRING,
    ORDER_ITEM_QUANTITY STRING,
    SALES STRING,
    ORDER_ITEM_TOTAL STRING,
    ORDER_PROFIT_PER_ORDER STRING,
    ORDER_REGION STRING,
    ORDER_STATE STRING,
    ORDER_STATUS STRING,
    ORDER_ZIPCODE STRING,
    PRODUCT_CARD_ID STRING,
    PRODUCT_CATEGORY_ID STRING,
    PRODUCT_DESCRIPTION STRING,
    PRODUCT_IMAGE STRING,
    PRODUCT_NAME STRING,
    PRODUCT_PRICE STRING,
    PRODUCT_STATUS STRING,
    SHIPPING_DATE_DATEORDERS STRING,
    SHIPPING_MODE STRING,
    _LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE_FILE STRING
)
CHANGE_TRACKING = TRUE;
    
-- To verify if the dataset exist
LIST @CPG_SUPPLY_CHAIN.UTILS.SUPPLY_CHAIN_STAGE;

-- Loading my data to my BRONZE_ORDERS table
COPY INTO BRONZE_ORDERS 
(
    TYPE, DAYS_FOR_SHIPPING_REAL, DAYS_FOR_SHIPMENT_SCHEDULED, BENEFIT_PER_ORDER,
    SALES_PER_CUSTOMER, DELIVERY_STATUS, LATE_DELIVERY_RISK, CATEGORY_ID, CATEGORY_NAME,
    CUSTOMER_CITY, CUSTOMER_COUNTRY, CUSTOMER_EMAIL, CUSTOMER_FNAME, CUSTOMER_ID,
    CUSTOMER_LNAME, CUSTOMER_PASSWORD, CUSTOMER_SEGMENT, CUSTOMER_STATE, CUSTOMER_STREET,
    CUSTOMER_ZIPCODE, DEPARTMENT_ID, DEPARTMENT_NAME, LATITUDE, LONGITUDE, MARKET,
    ORDER_CITY, ORDER_COUNTRY, ORDER_CUSTOMER_ID, ORDER_DATE_DATEORDERS, ORDER_ID,
    ORDER_ITEM_CARDPROD_ID, ORDER_ITEM_DISCOUNT, ORDER_ITEM_DISCOUNT_RATE, ORDER_ITEM_ID,
    ORDER_ITEM_PRODUCT_PRICE, ORDER_ITEM_PROFIT_RATIO, ORDER_ITEM_QUANTITY, SALES,
    ORDER_ITEM_TOTAL, ORDER_PROFIT_PER_ORDER, ORDER_REGION, ORDER_STATE, ORDER_STATUS,
    ORDER_ZIPCODE, PRODUCT_CARD_ID, PRODUCT_CATEGORY_ID, PRODUCT_DESCRIPTION, PRODUCT_IMAGE,
    PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STATUS, SHIPPING_DATE_DATEORDERS, SHIPPING_MODE,
    _SOURCE_FILE
)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
           $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,
           $39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,
           METADATA$FILENAME
    FROM @UTILS.SUPPLY_CHAIN_STAGE
    )
FILE_FORMAT = (FORMAT_NAME = UTILS.CSV_FF)
ON_ERROR = 'CONTINUE'
PATTERN = '.*\.csv';

