USE DATABASE CPG_SUPPLY_CHAIN;
USE SCHEMA GOLD;
-- Creates DIM_DATE dimension table
CREATE OR REPLACE TABLE DIM_DATE AS
SELECT 
    DATE_KEY,
    YEAR(DATE_KEY) AS YEAR,
    QUARTER(DATE_KEY) AS QUARTER,
    MONTH(DATE_KEY) AS MONTH,
    DAY(DATE_KEY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_KEY) AS DAY_OF_WEEK,
    DAYNAME(DATE_KEY) AS DAY_NAME,
    IFF(DAYOFWEEK(DATE_KEY) IN (0, 6), TRUE, FALSE) AS IS_WEEKEND
FROM(
    SELECT DATEADD(DAY, SEQ4(), '2015-01-01')::DATE AS DATE_KEY
    FROM TABLE(GENERATOR(ROWCOUNT => 3653))
    ) AS GENERATED_DATES -- ~10 years of datas from 2015-01-01

--1. Confirm DIM_DATE built correctly
SELECT COUNT(*) FROM DIM_DATE; 
-- expect 3653
SELECT MIN(DATE_KEY), MAX(DATE_KEY) FROM DIM_DATE;
-- expect 2015-01-01 to roughly 2024-12-31
SELECT * FROM DIM_DATE LIMIT 10; 
-- column spotting

-- Creates DIM_PRODUCT dimension table
CREATE OR REPLACE TABLE DIM_PRODUCT AS 
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY_NAME,
    DEPARTMENT_NAME,
    PRODUCT_PRICE
FROM (
    SELECT 
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY_NAME,
        DEPARTMENT_NAME,
        PRODUCT_PRICE,
        ROW_NUMBER() OVER (
            PARTITION BY PRODUCT_ID
            ORDER BY _LOAD_TS DESC
        ) AS RN
    FROM SILVER.SILVER_ORDERS
) AS DEDUPED
WHERE RN = 1;

-- Validation for DIM_PRODUCT
SELECT COUNT(*) FROM DIM_PRODUCT;
SELECT PRODUCT_ID, COUNT(*) FROM DIM_PRODUCT GROUP BY PRODUCT_ID HAVING COUNT(*) > 1;
SELECT * FROM DIM_PRODUCT LIMIT 10;

-- Creates DIM_CUSTOMER dimension table
CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_SEGMENT,
    CUSTOMER_CITY,
    CUSTOMER_STATE,
    CUSTOMER_COUNTRY
FROM (
    SELECT
        CUSTOMER_ID,
        CUSTOMER_SEGMENT,
        CUSTOMER_CITY,
        CUSTOMER_STATE,
        CUSTOMER_COUNTRY,
        ROW_NUMBER() OVER (
            PARTITION BY CUSTOMER_ID
            ORDER BY _LOAD_TS DESC
        ) AS RN
    FROM SILVER.SILVER_ORDERS
) AS DEDUPED
WHERE RN = 1;

-- DIM_CUSTOMER validation
SELECT COUNT(*) FROM DIM_CUSTOMER;
SELECT * FROM DIM_CUSTOMER ORDER BY CUSTOMER_ID DESC LIMIT 20;
SELECT CUSTOMER_ID, COUNT(*) FROM DIM_CUSTOMER GROUP BY CUSTOMER_ID HAVING COUNT(*) > 1;

-- Creation of DIM_SHIPPING_MODE dimension table
CREATE OR REPLACE TABLE DIM_SHIPPING_MODE AS
SELECT DISTINCT
    SHIPPING_MODE
FROM SILVER.SILVER_ORDERS
WHERE SHIPPING_MODE IS NOT NULL;
-- Validation for DIM_SHIPPING_MODE
SELECT COUNT(*) FROM DIM_SHIPPING_MODE
SELECT * FROM DIM_SHIPPING_MODE

-- Creation of FACT_ORDERS dimension table to complete the star schema.
CREATE OR REPLACE TABLE FACT_ORDERS AS
SELECT 
-- one row per order line item
    S.ORDER_ID,
    S.ORDER_ITEM_ID,

    -- Foreign keys for each dimension
    S.CUSTOMER_ID,
    S.PRODUCT_ID,
    S.SHIPPING_MODE,
    DATE(S.ORDER_TS) AS ORDER_DATE_KEY,
    DATE(S.SHIPPING_TS) AS SHIPPING_DATE_KEY,

    -- Order attributes (low cardinality)
    S.MARKET,
    S.ORDER_REGION,
    S.ORDER_STATUS,
    S.DELIVERY_STATUS,

    --Measures
    S.ORDER_ITEM_QUANTITY,
    S.SALES_AMOUNT,
    S.ORDER_ITEM_TOTAL,
    S.ORDER_ITEM_DISCOUNT,
    S.ORDER_ITEM_DISCOUNT_RATE,
    S.PROFIT_PER_ORDER,
    S.PROFIT_RATIO,
    S.DAYS_SHIPPING_ACTUAL,
    S.DAYS_SHIPPING_SCHEDULED,
    S.IS_LATE_DELIVERY_RISK
FROM SILVER.SILVER_ORDERS S;

-- Fact Table validation
-- should match with the quantity of silver orders (180519)
SELECT
    (SELECT COUNT(*) FROM SILVER.SILVER_ORDERS) AS SILVER_COUNT,
    (SELECT COUNT(*) FROM FACT_ORDERS) AS FACT_COUNT;

--checking if joining the dimensions are good
SELECT F.ORDER_ITEM_ID, P.PRODUCT_NAME, C.CUSTOMER_SEGMENT, D.YEAR, D.MONTH
FROM FACT_ORDERS F
JOIN DIM_PRODUCT P ON F.PRODUCT_ID = P.PRODUCT_ID
JOIN DIM_CUSTOMER C ON F.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DIM_DATE D ON F.ORDER_DATE_KEY = D.DATE_KEY
LIMIT 10;

-- Null checking expected is 0 for all columns
SELECT
    SUM(IFF(SALES_AMOUNT IS NULL, 1, 0))       AS NULL_SALES,
    SUM(IFF(PROFIT_PER_ORDER IS NULL, 1, 0))   AS NULL_PROFIT,
    SUM(IFF(ORDER_ITEM_QUANTITY IS NULL, 1, 0)) AS NULL_QUANTITY
FROM FACT_ORDERS;

-- Sample Aggregation
SELECT
    D.YEAR,
    COUNT(*) AS NUM_ORDER_ITEMS,
    SUM(F.SALES_AMOUNT) AS TOTAL_SALES,
    SUM(F.PROFIT_PER_ORDER) AS TOTAL_PROFIT
FROM FACT_ORDERS F
JOIN DIM_DATE D ON F.ORDER_DATE_KEY = D.DATE_KEY
GROUP BY D.YEAR
ORDER BY D.YEAR;

--Creation of Data marts
USE DATABASE CPG_SUPPLY_CHAIN;
USE SCHEMA GOLD;

CREATE OR REPLACE TABLE MART_PROFIT_BY_CATEGORY_REGION AS
SELECT
    P.CATEGORY_NAME,
    F.ORDER_REGION,
    COUNT(*)                        AS NUM_ORDER_ITEMS,
    SUM(F.SALES_AMOUNT)             AS TOTAL_SALES,
    SUM(F.PROFIT_PER_ORDER)         AS TOTAL_PROFIT,
    ROUND(SUM(F.PROFIT_PER_ORDER) / NULLIF(SUM(F.SALES_AMOUNT), 0) * 100, 2) AS PROFIT_MARGIN_PCT
FROM FACT_ORDERS F
JOIN DIM_PRODUCT P ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY_NAME, F.ORDER_REGION
ORDER BY TOTAL_SALES DESC;

SELECT * FROM MART_PROFIT_BY_CATEGORY_REGION ORDER BY PROFIT_MARGIN_PCT DESC LIMIT 10;
SELECT * FROM MART_PROFIT_BY_CATEGORY_REGION ORDER BY PROFIT_MARGIN_PCT ASC LIMIT 10;