USE DATABASE CPG_SUPPLY_CHAIN;
USE SCHEMA GOLD;
-- Creates DIM_DATE dimension table
CREATE OR REPLACE TABLE DIM_DATE AS
SELECT 
    DATE_KEY,
    YEAR(DATE_KEY) AS YEAR,
    QUARTER(DATE_KEY) AS QUARTER,
    MONTH(DATE_KEY) AS MONTH,
    DAY(DATE_KEY) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_KEY) AS DAY_OF_WEEK,
    DAYNAME(DATE_KEY) AS DAY_NAME,
    IFF(DAYOFWEEK(DATE_KEY) IN (0, 6), TRUE, FALSE) AS IS_WEEKEND
FROM(
    SELECT DATEADD(DAY, SEQ4(), '2015-01-01')::DATE AS DATE_KEY
    FROM TABLE(GENERATOR(ROWCOUNT => 3653))
    ) AS GENERATED_DATES -- ~10 years of datas from 2015-01-01

--1. Confirm DIM_DATE built correctly
SELECT COUNT(*) FROM DIM_DATE; 
-- expect 3653
SELECT MIN(DATE_KEY), MAX(DATE_KEY) FROM DIM_DATE;
-- expect 2015-01-01 to roughly 2024-12-31
SELECT * FROM DIM_DATE LIMIT 10; 
-- column spotting

-- Creates DIM_PRODUCT dimension table
CREATE OR REPLACE TABLE DIM_PRODUCT AS 
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY_NAME,
    DEPARTMENT_NAME,
    PRODUCT_PRICE
FROM (
    SELECT 
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY_NAME,
        DEPARTMENT_NAME,
        PRODUCT_PRICE,
        ROW_NUMBER() OVER (
            PARTITION BY PRODUCT_ID
            ORDER BY _LOAD_TS DESC
        ) AS RN
    FROM SILVER.SILVER_ORDERS
) AS DEDUPED
WHERE RN = 1;

-- Validation for DIM_PRODUCT
SELECT COUNT(*) FROM DIM_PRODUCT;
SELECT PRODUCT_ID, COUNT(*) FROM DIM_PRODUCT GROUP BY PRODUCT_ID HAVING COUNT(*) > 1;
SELECT * FROM DIM_PRODUCT LIMIT 10;