-- 1. Warehouse
CREATE WAREHOUSE IF NOT EXISTS CPG_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE CPG_WH;

-- 2. Database + medallion schemas
CREATE DATABASE IF NOT EXISTS CPG_SUPPLY_CHAIN;
USE DATABASE CPG_SUPPLY_CHAIN;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS UTILS;

-- 3. File format + stage
CREATE FILE FORMAT IF NOT EXISTS UTILS.CSV_FF
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  ENCODING = 'ISO-8859-1';

CREATE STAGE IF NOT EXISTS UTILS.SUPPLY_CHAIN_STAGE
  FILE_FORMAT = UTILS.CSV_FF;