USE DATABASE CPG_SUPPLY_CHAIN;
USE SCHEMA UTILS;

-- Stream Creation 
CREATE STREAM IF NOT EXISTS BRONZE_ORDERS_STREAM
ON TABLE BRONZE.BRONZE_ORDERS;

CREATE STREAM IF NOT EXISTS SILVER_ORDERS_STREAM
ON TABLE SILVER.SILVER_ORDERS;

SHOW STREAMS;

-- test if there's any change it should be false
SELECT SYSTEM$STREAM_HAS_DATA('BRONZE_ORDERS_STREAM');
SELECT SYSTEM$STREAM_HAS_DATA('SILVER_ORDERS_STREAM');

-- Orchaestration
-- be sure the pipeline_log was created in setup
-- note: it should be created from parent to child
SELECT * FROM CPG_SUPPLY_CHAIN.UTILS.PIPELINE_RUN_LOG LIMIT 5;

-- Bronze
CREATE OR REPLACE TASK TASK_LOAD_BRONZE
  WAREHOUSE = CPG_WH
  SCHEDULE = 'USING CRON 0 4 * * * Asia/Manila'  -- runs daily at 4am PHT
AS
BEGIN
    COPY INTO BRONZE.BRONZE_ORDERS (
        TYPE, DAYS_FOR_SHIPPING_REAL, DAYS_FOR_SHIPMENT_SCHEDULED, BENEFIT_PER_ORDER,
        SALES_PER_CUSTOMER, DELIVERY_STATUS, LATE_DELIVERY_RISK, CATEGORY_ID, CATEGORY_NAME,
        CUSTOMER_CITY, CUSTOMER_COUNTRY, CUSTOMER_EMAIL, CUSTOMER_FNAME, CUSTOMER_ID,
        CUSTOMER_LNAME, CUSTOMER_PASSWORD, CUSTOMER_SEGMENT, CUSTOMER_STATE, CUSTOMER_STREET,
        CUSTOMER_ZIPCODE, DEPARTMENT_ID, DEPARTMENT_NAME, LATITUDE, LONGITUDE, MARKET,
        ORDER_CITY, ORDER_COUNTRY, ORDER_CUSTOMER_ID, ORDER_DATE_DATEORDERS, ORDER_ID,
        ORDER_ITEM_CARDPROD_ID, ORDER_ITEM_DISCOUNT, ORDER_ITEM_DISCOUNT_RATE, ORDER_ITEM_ID,
        ORDER_ITEM_PRODUCT_PRICE, ORDER_ITEM_PROFIT_RATIO, ORDER_ITEM_QUANTITY, SALES,
        ORDER_ITEM_TOTAL, ORDER_PROFIT_PER_ORDER, ORDER_REGION, ORDER_STATE, ORDER_STATUS,
        ORDER_ZIPCODE, PRODUCT_CARD_ID, PRODUCT_CATEGORY_ID, PRODUCT_DESCRIPTION, PRODUCT_IMAGE,
        PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STATUS, SHIPPING_DATE_DATEORDERS, SHIPPING_MODE,
        _SOURCE_FILE
    )
    FROM (
        SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
               $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,
               $39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51,$52,$53,
               METADATA$FILENAME
        FROM @UTILS.SUPPLY_CHAIN_STAGE
    )
    FILE_FORMAT = (FORMAT_NAME = UTILS.CSV_FF)
    ON_ERROR = 'CONTINUE'
    PATTERN = '.*\.csv';

    INSERT INTO UTILS.PIPELINE_RUN_LOG (TASK_NAME, LAYER, STATUS, ROW_COUNT, STARTED_AT)
    SELECT 'TASK_LOAD_BRONZE', 'BRONZE', 'SUCCESS', COUNT(*), CURRENT_TIMESTAMP()
    FROM BRONZE.BRONZE_ORDERS;
END;

-- Silver
CREATE OR REPLACE TASK TASK_TRANSFORM_SILVER
  WAREHOUSE = CPG_WH
  AFTER TASK_LOAD_BRONZE
  WHEN SYSTEM$STREAM_HAS_DATA('BRONZE_ORDERS_STREAM')
AS
BEGIN
    MERGE INTO SILVER.SILVER_ORDERS AS TGT
    USING (
        SELECT
            TRY_TO_NUMBER(ORDER_ID)                                AS ORDER_ID,
            TRY_TO_NUMBER(ORDER_ITEM_ID)                           AS ORDER_ITEM_ID,
            TRY_TO_NUMBER(CUSTOMER_ID)                             AS CUSTOMER_ID,
            CUSTOMER_SEGMENT, CUSTOMER_CITY, CUSTOMER_STATE, CUSTOMER_COUNTRY,
            TRY_TO_NUMBER(PRODUCT_CARD_ID)                         AS PRODUCT_ID,
            PRODUCT_NAME, CATEGORY_NAME, DEPARTMENT_NAME,
            TRY_TO_DECIMAL(PRODUCT_PRICE, 12, 2)                   AS PRODUCT_PRICE,
            MARKET, ORDER_REGION, ORDER_COUNTRY, ORDER_STATE, ORDER_CITY, ORDER_STATUS,
            TRY_TO_TIMESTAMP_NTZ(ORDER_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI')    AS ORDER_TS,
            TRY_TO_TIMESTAMP_NTZ(SHIPPING_DATE_DATEORDERS, 'MM/DD/YYYY HH24:MI') AS SHIPPING_TS,
            SHIPPING_MODE,
            TRY_TO_NUMBER(DAYS_FOR_SHIPPING_REAL)                  AS DAYS_SHIPPING_ACTUAL,
            TRY_TO_NUMBER(DAYS_FOR_SHIPMENT_SCHEDULED)             AS DAYS_SHIPPING_SCHEDULED,
            IFF(TRY_TO_NUMBER(LATE_DELIVERY_RISK) = 1, TRUE, FALSE) AS IS_LATE_DELIVERY_RISK,
            DELIVERY_STATUS,
            TRY_TO_NUMBER(ORDER_ITEM_QUANTITY)                     AS ORDER_ITEM_QUANTITY,
            TRY_TO_DECIMAL(SALES, 12, 2)                           AS SALES_AMOUNT,
            TRY_TO_DECIMAL(ORDER_ITEM_TOTAL, 12, 2)                AS ORDER_ITEM_TOTAL,
            TRY_TO_DECIMAL(ORDER_ITEM_DISCOUNT, 12, 2)             AS ORDER_ITEM_DISCOUNT,
            TRY_TO_DECIMAL(ORDER_ITEM_DISCOUNT_RATE, 6, 4)         AS ORDER_ITEM_DISCOUNT_RATE,
            TRY_TO_DECIMAL(BENEFIT_PER_ORDER, 12, 2)               AS PROFIT_PER_ORDER,
            TRY_TO_DECIMAL(ORDER_ITEM_PROFIT_RATIO, 6, 4)          AS PROFIT_RATIO,
            _LOAD_TS, _SOURCE_FILE
        FROM BRONZE_ORDERS_STREAM
        WHERE ORDER_ID IS NOT NULL
        QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ITEM_ID ORDER BY _LOAD_TS DESC) = 1
    ) AS SRC
    ON TGT.ORDER_ITEM_ID = SRC.ORDER_ITEM_ID
    WHEN MATCHED THEN UPDATE SET
        TGT.SALES_AMOUNT = SRC.SALES_AMOUNT, TGT.PROFIT_PER_ORDER = SRC.PROFIT_PER_ORDER,
        TGT._LOAD_TS = SRC._LOAD_TS
    WHEN NOT MATCHED THEN INSERT VALUES (
        SRC.ORDER_ID, SRC.ORDER_ITEM_ID, SRC.CUSTOMER_ID, SRC.CUSTOMER_SEGMENT,
        SRC.CUSTOMER_CITY, SRC.CUSTOMER_STATE, SRC.CUSTOMER_COUNTRY, SRC.PRODUCT_ID,
        SRC.PRODUCT_NAME, SRC.CATEGORY_NAME, SRC.DEPARTMENT_NAME, SRC.PRODUCT_PRICE,
        SRC.MARKET, SRC.ORDER_REGION, SRC.ORDER_COUNTRY, SRC.ORDER_STATE, SRC.ORDER_CITY,
        SRC.ORDER_STATUS, SRC.ORDER_TS, SRC.SHIPPING_TS, SRC.SHIPPING_MODE,
        SRC.DAYS_SHIPPING_ACTUAL, SRC.DAYS_SHIPPING_SCHEDULED, SRC.IS_LATE_DELIVERY_RISK,
        SRC.DELIVERY_STATUS, SRC.ORDER_ITEM_QUANTITY, SRC.SALES_AMOUNT, SRC.ORDER_ITEM_TOTAL,
        SRC.ORDER_ITEM_DISCOUNT, SRC.ORDER_ITEM_DISCOUNT_RATE, SRC.PROFIT_PER_ORDER,
        SRC.PROFIT_RATIO, SRC._LOAD_TS, SRC._SOURCE_FILE
    );

    INSERT INTO UTILS.PIPELINE_RUN_LOG (TASK_NAME, LAYER, STATUS, ROW_COUNT, STARTED_AT)
    SELECT 'TASK_TRANSFORM_SILVER', 'SILVER', 'SUCCESS', COUNT(*), CURRENT_TIMESTAMP()
    FROM SILVER.SILVER_ORDERS;
END;

-- Gold 
CREATE OR REPLACE TASK TASK_REFRESH_GOLD
    WAREHOUSE = CPG_WH
    AFTER TASK_TRANSFORM_SILVER
    -- to check if there's new data
    WHEN SYSTEM$STREAM_HAS_DATA('SILVER_ORDERS_STREAM')
AS 
-- Procedure
BEGIN
    CREATE OR REPLACE TABLE GOLD.FACT_ORDERS AS
    SELECT
        ORDER_ID, ORDER_ITEM_ID, CUSTOMER_ID, PRODUCT_ID, SHIPPING_MODE,
        DATE(ORDER_TS) AS ORDER_DATE_KEY, DATE(SHIPPING_TS) AS SHIPPING_DATE_KEY,
        MARKET, ORDER_REGION, ORDER_STATUS, DELIVERY_STATUS,
        ORDER_ITEM_QUANTITY, SALES_AMOUNT, ORDER_ITEM_TOTAL, ORDER_ITEM_DISCOUNT,
        ORDER_ITEM_DISCOUNT_RATE, PROFIT_PER_ORDER, PROFIT_RATIO,
        DAYS_SHIPPING_ACTUAL, DAYS_SHIPPING_SCHEDULED, IS_LATE_DELIVERY_RISK
    FROM SILVER.SILVER_ORDERS;
-- historical log
    INSERT INTO UTILS.PIPELINE_RUN_LOG (TASK_NAME, LAYER, STATUS, ROW_COUNT, STARTED_AT)
    SELECT 'TASK_REFRESH_GOLD','GOLD','SUCCESS', COUNT(*), CURRENT_TIMESTAMP()
    FROM GOLD.FACT_ORDERS;
END;

-- to show tasks all should be suspended
SHOW TASKS;

ALTER TASK TASK_REFRESH_GOLD RESUME;
ALTER TASK TASK_TRANSFORM_SILVER RESUME;
ALTER TASK TASK_LOAD_BRONZE RESUME;

-- Manual trigger the pipeline
EXECUTE TASK TASK_LOAD_BRONZE;

-- Checking the if newly uploaded file is good
SELECT FILE_NAME, LAST_LOAD_TIME, ROW_COUNT
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'CPG_SUPPLY_CHAIN.BRONZE.BRONZE_ORDERS',
    START_TIME => DATEADD(DAY, -30, CURRENT_TIMESTAMP())
));